# Generated by Django 3.2.18 on 2023-04-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellerApp', '0002_auto_20230326_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
