# Generated by Django 3.2.18 on 2023-08-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellerApp', '0003_trip_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
