# Generated by Django 3.2.18 on 2023-08-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravellerApp', '0004_auto_20230820_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='guide',
            field=models.TextField(),
        ),
    ]
